import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { Toaster } from "../components/ui/sonner";
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
weight: ["400", "500"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
     <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col">{children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
